server:
  servlet:
    session:
      tracking-modes: cookie
#  error:
#    whitelabel:
#      enabled: false
#    include-exception: true
#    include-message: always
  port: 8000

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/term
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: drop
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 50
        show_sql: true
        format_sql: true
      defer-datasource-initialization: true

# 데이터 삽입 -> always / 그 외 -> never
  sql:
    init:
      mode: never
#      mode: always