server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
  port: 8081

spring:
  messages:
    basename: errors

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/term
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
